import {
  createContext,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    home: "Home",
    about: "About",
    skills: "Skills",
    projects: "Projects",
    experience: "Experience",
    education: "Education",
    hobbies: "Hobbies",
    testimonials: "Testimonials",
    contact: "Contact",
    messages: "Messages",
    resume: "Resume",
    language: "Language",
    english: "English",
    french: "French",
    downloadCV: "Download CV",
    viewCV: "View CV",
    login: "Login",
    logout: "Logout",
    admin: "Admin",
    dashboard: "Dashboard",
    submit: "Submit",
    send: "Send",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    success: "Success",
    adminPanel: "Admin Panel",
    backToSite: "Back to Site",
    name: "Name",
    email: "Email",
    phone: "Phone",
    location: "Location",
    description: "Description",
    category: "Category",
    level: "Level",
    actions: "Actions",
    status: "Status",
    startDate: "Start Date",
    currentlyWorking: "Currently working here",
    message: "Message",
    subject: "Subject",
    company: "Company",
    position: "Position",
    signIn: "Sign In",
    viewProjects: "View Projects",
    viewAllProjects: "View All Projects",
    contactMe: "Contact Me",
    ctaTitle: "Ready to work together?",
    ctaSubtitle: "Let's create something amazing",
    getInTouch: "Get In Touch",
    heroWelcome: "Welcome to my portfolio",
    heroSubtitle: "Student & Junior Full-Stack Developer",
    skillsTag: "WHAT I DO",
    skillsTitle: "Skills & Expertise",
    skillsSubtitle: "Technologies and tools I've mastered throughout my career",
    projectsTag: "MY WORK",
    projectsTitle: "Featured Projects",
    projectsSubtitle:
      "A selection of projects I've worked on, from web apps to AI tools",
    experienceTag: "MY JOURNEY",
    experienceTitle: "Work Experience",
    experienceSubtitle: "My professional journey through the tech industry",
    educationTag: "LEARNING PATH",
    educationTitle: "Education & Certifications",
    educationSubtitle: "Academic background and continuous learning",
    educationDegrees: "Academic Degrees",
    educationCertifications: "Certifications",
    educationCourses: "Continuous Learning",
    hobbiesTag: "BEYOND CODE",
    hobbiesTitle: "Hobbies & Interests",
    hobbiesSubtitle: "What I do when I'm not behind a keyboard",
    hobbiesFunFacts: "Fun Facts",
    hobbiesFactTravel: "Travel on Bike this year",
    hobbiesFactSwim: "Favourite Swimming Distance",
    hobbiesFactTrip: "Was my last trip",
    testimonialsTag: "FEEDBACK",
    testimonialsTitle: "Testimonials",
    testimonialsSubtitle: "What people say about working with me",
    testimonialsShareTag: "SHARE YOUR EXPERIENCE",
    testimonialsLeaveTitle: "Leave a Testimonial",
    testimonialsLeaveSubtitle:
      "Have worked with me? I’d love to hear about your experience!",
    testimonialsShareTitle: "Share Your Testimonial",
    testimonialsShareSubtitle:
      "Help others learn from your experience working with me",
    testimonialsYourName: "Your Name",
    testimonialsNamePlaceholder: "Enter your name",
    testimonialsTitleEn: "Title/Position (EN)",
    testimonialsTitleFr: "Title/Position (FR)",
    testimonialsTitlePlaceholder: "e.g., Product Manager, Team Lead",
    testimonialsTitlePlaceholderFr: "e.g., Product Manager, Team Lead",
    testimonialsCompanyEn: "Company (EN)",
    testimonialsCompanyFr: "Company (FR)",
    testimonialsCompanyPlaceholder: "e.g., Google, Microsoft",
    testimonialsCompanyPlaceholderFr: "e.g., Google, Microsoft",
    testimonialsRating: "Rating",
    ratingPoor: "Poor",
    ratingFair: "Fair",
    ratingGood: "Good",
    ratingGreat: "Great",
    ratingExcellent: "Excellent",
    testimonialsContentEn: "Testimonial (EN)",
    testimonialsContentFr: "Testimonial (FR)",
    testimonialsContentPlaceholder: "Share your experience and thoughts...",
    testimonialsContentPlaceholderFr: "Share your experience and thoughts...",
    testimonialsSubmit: "Submit Testimonial",
    testimonialsSubmitting: "Submitting...",
    testimonialsSubmitSuccess:
      "Testimonial submitted successfully! It will be reviewed and published shortly.",
    testimonialsSubmitError: "Failed to submit testimonial. Please try again.",
    at: "at",
    contactTag: "GET IN TOUCH",
    contactTitle: "Let's Talk",
    contactSubtitle: "Have a project in mind? I would love to hear from you.",
    contactNamePlaceholder: "Your name",
    contactEmailPlaceholder: "your@email.com",
    contactSubjectPlaceholder: "What is this about?",
    contactMessagePlaceholder: "Tell me about your project...",
    contactSuccess: "Message sent successfully!",
    contactSend: "Send Message",
    contactSending: "Sending...",
    contactSendError: "Failed to send message. Please try again later.",
    contactConnect: "Connect With Me",
    contactAvailable: "Available for work",
    contactAvailability: "Currently accepting new projects and collaborations",
    footerRights: "All rights reserved.",
    loading: "Loading...",
    loadingSkills: "Loading skills...",
    loadingProjects: "Loading projects...",
    loadingExperiences: "Loading experiences...",
    loadingEducation: "Loading education...",
    loadingHobbies: "Loading hobbies...",
    loadingTestimonials: "Loading testimonials...",
    loadError: "Failed to load data. Please try again later.",
    noSkills: "No skills found. Add your first skill to get started!",
    categoryFrontend: "Frontend",
    categoryBackend: "Backend",
    categoryDevops: "DevOps",
    currentRole: "Present",
    nameEn: "Name (EN)",
    nameFr: "Name (FR)",
    descriptionEn: "Description (EN)",
    descriptionFr: "Description (FR)",
    titleEn: "Title (EN)",
    titleFr: "Title (FR)",
    companyEn: "Company (EN)",
    companyFr: "Company (FR)",
    locationEn: "Location (EN)",
    locationFr: "Location (FR)",
    responsibilitiesEn: "Responsibilities (EN)",
    responsibilitiesFr: "Responsibilities (FR)",
    addSkill: "Add Skill",
    manageSkills: "Manage Skills",
    updateSkill: "Update Skill",
    createSkill: "Create Skill",
    addExperience: "Add Experience",
    manageExperience: "Manage Experience",
    update: "Update",
    create: "Create",
    areYouSure: "Are you sure?",
    approve: "Approve",
    reject: "Reject",
    confirmReject: "Confirm Reject",
    rejectionReason: "Rejection reason",
  },
  fr: {
    home: "Accueil",
    about: "À propos",
    skills: "Compétences",
    projects: "Projets",
    experience: "Expérience",
    education: "Éducation",
    hobbies: "Loisirs",
    testimonials: "Témoignages",
    contact: "Contact",
    messages: "Messages",
    resume: "CV",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    downloadCV: "Télécharger CV",
    viewCV: "Voir CV",
    login: "Connexion",
    logout: "Déconnexion",
    admin: "Admin",
    dashboard: "Tableau de bord",
    submit: "Soumettre",
    send: "Envoyer",
    cancel: "Annuler",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    success: "Succès",
    adminPanel: "Panneau d'administration",
    backToSite: "Retour au site",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    location: "Lieu",
    description: "Description",
    category: "Catégorie",
    level: "Niveau",
    actions: "Actions",
    status: "Statut",
    startDate: "Date de début",
    currentlyWorking: "Travaille actuellement ici",
    message: "Message",
    subject: "Sujet",
    company: "Entreprise",
    position: "Poste",
    signIn: "Se connecter",
    viewProjects: "Voir les projets",
    viewAllProjects: "Voir tous les projets",
    contactMe: "Me contacter",
    ctaTitle: "Prêt à travailler ensemble ?",
    ctaSubtitle: "Créons quelque chose d’incroyable",
    getInTouch: "Contactez-moi",
    heroWelcome: "Bienvenue sur mon portfolio",
    heroSubtitle: "Étudiant et développeur full-stack junior",
    skillsTag: "CE QUE JE FAIS",
    skillsTitle: "Compétences & Expertise",
    skillsSubtitle: "Technologies et outils maîtrisés au fil de ma carrière",
    projectsTag: "MES RÉALISATIONS",
    projectsTitle: "Projets phares",
    projectsSubtitle:
      "Une sélection de projets web et IA sur lesquels j’ai travaillé",
    experienceTag: "MON PARCOURS",
    experienceTitle: "Expérience professionnelle",
    experienceSubtitle: "Mon parcours à travers l’industrie technologique",
    educationTag: "PARCOURS SCOLAIRE",
    educationTitle: "Éducation & Certifications",
    educationSubtitle: "Formation académique et apprentissage continu",
    educationDegrees: "Diplômes académiques",
    educationCertifications: "Certifications",
    educationCourses: "Apprentissage continu",
    hobbiesTag: "AU-DELÀ DU CODE",
    hobbiesTitle: "Loisirs & Intérêts",
    hobbiesSubtitle: "Ce que je fais quand je ne code pas",
    hobbiesFunFacts: "Faits amusants",
    hobbiesFactTravel: "Voyage à vélo cette année",
    hobbiesFactSwim: "Distance de nage favorite",
    hobbiesFactTrip: "Était mon dernier voyage",
    testimonialsTag: "RETOURS",
    testimonialsTitle: "Témoignages",
    testimonialsSubtitle: "Ce que les gens disent de notre collaboration",
    testimonialsShareTag: "PARTAGEZ VOTRE EXPÉRIENCE",
    testimonialsLeaveTitle: "Laisser un témoignage",
    testimonialsLeaveSubtitle:
      "Vous avez travaillé avec moi ? J’aimerais connaître votre avis !",
    testimonialsShareTitle: "Partagez votre témoignage",
    testimonialsShareSubtitle:
      "Aidez les autres à découvrir votre expérience de collaboration",
    testimonialsYourName: "Votre nom",
    testimonialsNamePlaceholder: "Entrez votre nom",
    testimonialsTitleEn: "Titre/Poste (EN)",
    testimonialsTitleFr: "Titre/Poste (FR)",
    testimonialsTitlePlaceholder: "ex. Product Manager, Team Lead",
    testimonialsTitlePlaceholderFr: "ex. Chef de produit, Lead équipe",
    testimonialsCompanyEn: "Entreprise (EN)",
    testimonialsCompanyFr: "Entreprise (FR)",
    testimonialsCompanyPlaceholder: "ex. Google, Microsoft",
    testimonialsCompanyPlaceholderFr: "ex. Google, Microsoft",
    testimonialsRating: "Évaluation",
    ratingPoor: "Mauvais",
    ratingFair: "Passable",
    ratingGood: "Bon",
    ratingGreat: "Très bien",
    ratingExcellent: "Excellent",
    testimonialsContentEn: "Témoignage (EN)",
    testimonialsContentFr: "Témoignage (FR)",
    testimonialsContentPlaceholder:
      "Partagez votre expérience et vos impressions...",
    testimonialsContentPlaceholderFr:
      "Partagez votre expérience et vos impressions...",
    testimonialsSubmit: "Envoyer le témoignage",
    testimonialsSubmitting: "Envoi en cours...",
    testimonialsSubmitSuccess:
      "Témoignage envoyé avec succès ! Il sera bientôt examiné et publié.",
    testimonialsSubmitError:
      "Impossible d'envoyer le témoignage. Veuillez réessayer.",
    at: "chez",
    contactTag: "CONTACT",
    contactTitle: "Discutons",
    contactSubtitle: "Un projet en tête ? J’aimerais en discuter.",
    contactNamePlaceholder: "Votre nom",
    contactEmailPlaceholder: "vous@email.com",
    contactSubjectPlaceholder: "De quoi s’agit-il ?",
    contactMessagePlaceholder: "Parlez-moi de votre projet...",
    contactSuccess: "Message envoyé avec succès !",
    contactSend: "Envoyer le message",
    contactSending: "Envoi en cours...",
    contactSendError:
      "Impossible d'envoyer le message. Veuillez réessayer plus tard.",
    contactConnect: "Connectons-nous",
    contactAvailable: "Disponible pour travailler",
    contactAvailability: "Ouvert aux nouveaux projets et collaborations",
    footerRights: "Tous droits réservés.",
    loading: "Chargement...",
    loadingSkills: "Chargement des compétences...",
    loadingProjects: "Chargement des projets...",
    loadingExperiences: "Chargement des expériences...",
    loadingEducation: "Chargement des études...",
    loadingHobbies: "Chargement des loisirs...",
    loadingTestimonials: "Chargement des témoignages...",
    loadError:
      "Impossible de charger les données. Veuillez réessayer plus tard.",
    noSkills:
      "Aucune compétence trouvée. Ajoutez votre première compétence pour commencer !",
    categoryFrontend: "Frontend",
    categoryBackend: "Backend",
    categoryDevops: "DevOps",
    currentRole: "Présent",
    nameEn: "Nom (EN)",
    nameFr: "Nom (FR)",
    descriptionEn: "Description (EN)",
    descriptionFr: "Description (FR)",
    titleEn: "Titre (EN)",
    titleFr: "Titre (FR)",
    companyEn: "Entreprise (EN)",
    companyFr: "Entreprise (FR)",
    locationEn: "Lieu (EN)",
    locationFr: "Lieu (FR)",
    responsibilitiesEn: "Responsabilités (EN)",
    responsibilitiesFr: "Responsabilités (FR)",
    addSkill: "Ajouter une compétence",
    manageSkills: "Gérer les compétences",
    updateSkill: "Mettre à jour la compétence",
    createSkill: "Créer la compétence",
    addExperience: "Ajouter une expérience",
    manageExperience: "Gérer l’expérience",
    update: "Mettre à jour",
    create: "Créer",
    areYouSure: "Êtes-vous sûr ?",
    approve: "Approuver",
    reject: "Rejeter",
    confirmReject: "Confirmer le rejet",
    rejectionReason: "Raison du rejet",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const storedLanguage =
      (localStorage.getItem("language") as Language) || "en";
    setLanguage(storedLanguage);
  }, []);

  const setLanguageAndStore = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: setLanguageAndStore, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
